# H2
spring.datasource.url=jdbc:h2:mem:academo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Desabilita Flyway
spring.flyway.enabled=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desabilita Quartz JDBC (opcional)
spring.quartz.auto-startup=false
#spring.quartz.job-store-type=memory
