# spring.profiles.active=dev

spring.application.name=Academo

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.liquibase=INFO
logging.level.liquibase.sql=DEBUG

#Resend Mail
resend.service.api.key=${RESEND_API_KEY}
resend.academo.mail=${RESEND_ACADEMO_MAIL}

#Supbase Storage
storage.endpoint=${SUPABASE_ENDPOINT}
storage.region=${SUPABASE_REGION}
storage.access-key=${SUPABASE_ACCESS_KEY}
storage.secret-key=${SUPABASE_SECRET_KEY}
storage.bucket=${SUPABASE_BUCKET}

#GoogleDrive Storage
credentials.path=${GOOGLE_CREDENTIALS_PATH}
client.secrets=${GOOGLE_CLIENT_SECRETS}

api.security.token.jwt.secret=${JWT_SECRET}
api.security.token.activation.secret=${ACTIVATION_SECRET}
api.security.token.reset-password.secret=${RESET_PASSWORD_SECRET}

#spring.quartz.job-store-type = jdbc
jdbc.initialize-schema= never
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#spring.quartz.properties.org.quartz.threadPool.threadCount = 5
#config para criar as tabelas do quartz
#spring.quartz.jdbc.initialize-schema=always

#FileTransfer
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.file-size-threshold=2KB
#spring.servlet.multipart.max-file-size=25MB
#spring.servlet.multipart.max-request-size=30MB

file.upload-dir=src/main/resources/requests/uploads