spring.profiles.active=dev

spring.application.name=Academo

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.out-of-order=true
spring.flyway.enabled=true

api.security.token.secret=${JWT_SECRET:my-secret-key}

spring.quartz.job-store-type = jdbc
jdbc.initialize-schema= never
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.threadPool.threadCount = 5

#FileTransfer
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

file.upload-dir=src/main/resources/requests/uploads